config/routes.rb
Rails.application.routes.draw do
  root 'phone_number_in_word#index'
  resources :phone_number_in_word, only: [:create, :index]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phone_number_in_word_controller.rb
class PhoneNumberInWordController < ApplicationController
  def index
  	if $dictionarywords.blank?
  		$dictionarywords = {}

		File.open("/usr/share/dict/words") do |file|
		  file.each do |line|
		    $dictionarywords[line.strip] = true
		  end
		end
	end
  end

  def create
  	index
  	starttime = Time.now
  	if params[:phonenumber].present?
  		if params[:phonenumber] =~ /^\d+$/
  	        @output = SearchWord.start(params[:phonenumber])
  	    else
  	    	@error = "is not a phone number"
  	    end
  	else
  		@error = "Please Enter 10 digit phone number."
  	end
  	endtime = Time.now
  	@totaltime = endtime - starttime
  	render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_number_in_word_helper.rb
module PhoneNumberInWordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Numberintoword</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phone_number_in_word/index.html.erb
<h3>Search Word From Phone Number</h3>
<%= form_tag phone_number_in_word_index_path do %>
<h4>Please Enter 10 Digit Phone Number</h4>
	<p>
		<%= text_field_tag :phonenumber, (params[:phonenumber] if @error), class: "numeric", maxlength: 10 %> 
		<%= @error if @error.present? %>
	</p>
	<%= submit_tag "Submit" %>
<% end %>

<%- if @output %>
	<h4> Input Phone Number:: <%= params[:phonenumber]%></h4>
	<h4> Output: </h4>
	<p>Total Time Taken:: <%= @totaltime if @totaltime %> Sec.</p>
	<p><%= @output %></p>
<% end %>

<script type="text/javascript">
	$(document).on("input", ".numeric", function() {
	    this.value = this.value.replace(/[^\d\.\-]/g,'');
	});

</script>